export const offersdata =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999 PKR',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Dell XPS 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Sleek design, high performance.',
      price: '49999 PKR',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Apple iPad Air",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '29999 PKR',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '79999 PKR',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Samsung Galaxy",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '19999 PKR',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '69999 PKR',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Apple MacBook",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Elegant, powerful, and premium.',
      price: '29999 PKR',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Microsoft Surface",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '49999 PKR',
    },
    {
      id: 8,
      category: 'laptops',
      title: "HP Envy Series",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Stylish, intuitive, and powerful.',
      price: '89999 PKR',
    },


  ]